#!/usr/bin/env python3
"""Helper script to write SUMMARY.md — invoked by synthesizer."""
import os

out = "D:/claude/Autopilot/.planning/research/SUMMARY.md"

lines = [
    "# Project Research Summary",
    "",
    "**Project:** v1.10 macOS Platform SSO Follow-ons (Kerberos, Graph API, NUAL)",
    "**Domain:** Documentation information architecture -- three deferred PSSO surfaces landing as content guides in an existing macOS Intune documentation suite",
    "**Researched:** 2026-06-22",
    "**Confidence:** HIGH across all four research axes -- all v1.10 surfaces verified from authoritative primary sources",
    "",
    "## Executive Summary",
    "",
    "v1.10 is a content-only documentation milestone that closes three deferred items from v1.9 (PSSO-FUT-01, PSSO-FUT-02, PSSO-FUT-04). All three research questions that were left open at v1.9 close are now fully resolved: the NUAL MDM plist key literals are confirmed from Apple's authoritative `device-management` schema (PSSO-FUT-01 is closeable); the `platformCredentialAuthenticationMethod` Graph API is GA in v1.0 -- not beta (PSSO-FUT-02 is documentable); and the Apple Kerberos SSO extension identifier, payload type, Intune deployment path, and macOS version floor are all verified from Microsoft Learn and Apple deployment documentation (PSSO-FUT-04 is writeable). Multi-tenant PSSO (PSSO-FUT-03) remains explicitly out of scope for this milestone per the adversarial-review decision.",
    "",
    "The recommended build order mirrors the per-platform precedent established in v1.9: foundation content first (Kerberos guide + guide 09 surgical edit + glossary), then the remaining content surfaces (Graph API doc + NUAL key table update), then reference layer (capability matrix + L2 runbooks), then navigation integration last, and finally the harness lineage bump as the close phase. This order ensures that nav-hub files never link to content that does not yet exist, and that the harness apex inherits a stable chain state. One unresolved roadmap decision -- whether to place the Graph API doc in `docs/admin-setup-macos/11-...` (Option A, recommended) or a new `docs/operations/platform-credential/` subtree (Option B) -- should be confirmed at requirements or roadmap time.",
    "",
    "The primary execution-time risk is the pre-existing chain-red state: 10 legacy FAILs in validators for phases 58-66 and 73 are documented in `v1.9-DEFERRED-CLEANUP.md` as PRE-EXISTING-CHAIN-RED-AT-HEAD-01. The roadmap must schedule a decision -- either a dedicated chain-health pass before the v1.10 harness-lineage bump, or an explicitly documented rationale for routing the red chain forward. Masking the legacy FAILs via `CHAIN_SKIP` expansion is prohibited. All other risks are well-mitigated by existing suite conventions (navigation-last invariant, pre-edit anchor inventory, atomic commit for capability matrix + harness validator update).",
    "",
    "---",
    "",
    "## Key Findings",
    "",
    "### Recommended Stack",
    "",
    "v1.10 produces documentation artifacts only: Markdown files, `.mobileconfig` XML payload examples, PowerShell SDK code snippets, and HTTP request examples. The tool stack is the existing suite authoring environment (Markdown, GitHub-flavored callout syntax `> [!WARNING]`, Mermaid diagrams in `00-overview.md`, the existing validator/harness JavaScript infrastructure). No new authoring technologies are introduced.",
    "",
    "The three new technical surfaces are thoroughly researched and require no tooling decisions beyond existing suite conventions. All technical facts -- extension identifiers, API endpoint paths, MDM plist key literals, required permissions -- are verified from authoritative primary sources and are stable (GA or Apple `release` branch).",
    "",
    "**Core technologies (documentation layer):**",
    "- Markdown with GitHub-flavored callout syntax -- all new guides follow the existing suite format",
    "- Mermaid diagram extension -- `00-overview.md` requires a node addition for guide 10 (and optionally guide 11)",
    "- PowerShell `Microsoft.Graph.Identity.SignIns` module -- required for Graph API PowerShell SDK examples in the Graph API doc",
    "- JavaScript (Node.js) validators -- existing harness infrastructure; v1.10 adds `check-phase-83..NN.mjs` and `v1.10-milestone-audit.mjs` via the established Path-A pattern",
    "",
    "**Critical version requirements:**",
    "- macOS 14.6 Sonoma minimum -- required for PSSO + Kerberos TGT integration (`usePlatformSSOTGT: true`); standalone Kerberos extension works on macOS 10.15+ but is out of v1.10 scope",
    "- Company Portal 5.2408.0 or later -- required for PSSO Kerberos integration per Microsoft Entra Kerberos tutorial",
    "- Company Portal 2508+ -- required for `custom_tgt_setting` TGT mapping control key (optional advanced feature)",
    "- Microsoft Graph v1.0 -- `platformCredentialAuthenticationMethod` and all three operations (List, Get, Delete) are GA in v1.0; use `https://graph.microsoft.com/v1.0/` exclusively",
    "",
    "### Expected Features",
    "",
    "The three content surfaces translate directly to five deliverables with a fixed scope boundary.",
    "",
    "**Must have (PSSO-FUT closes):**",
    "- Guide `10-kerberos-sso-extension.md` -- full Kerberos SSO extension guide: extension identifier, realm/hosts config, Intune Custom Template deployment path, PSSO TGT-sharing integration, `app-sso platform -s` diagnostic output interpretation, browser configuration matrix; closes PSSO-FUT-04",
    "- Guide `08-auth-methods-deep-dive.md` surgical edit -- add verified MDM plist key literals (`NewUserAuthorizationMode`, `UserAuthorizationMode`) to the NUAL Settings Catalog table; remove the deferred-item callout blockquote; closes PSSO-FUT-01",
    "- Graph API Platform Credential doc (new file at Option A or B location) -- `platformCredentialAuthenticationMethod` resource reference, List/Get/Delete operations with HTTP and PowerShell examples, permissions matrix, `[!WARNING]` callout on DELETE, leaver/offboarding automation pattern; closes PSSO-FUT-02",
    "",
    "**Should have (integration layer):**",
    "- L2 runbook `28-macos-kerberos-sso-investigation.md` -- TGT failure triage, ticket-cache inspection, realm error diagnosis",
    "- L2 runbook `29-macos-graph-credential-investigation.md` -- enumerate/query/delete credential workflow, API error interpretation",
    "- Capability matrix update -- Kerberos SSO Extension row added to `macos-capability-matrix.md`",
    "- Glossary entries -- Kerberos SSO Extension and Platform Credential Graph API terms in `_glossary-macos.md`",
    "- Guide 09 surgical edit -- replace deferred-item sentence at `## Kerberos SSO Extension (Coexistence)` with forward link to guide 10",
    "- Nav-hub integration -- `docs/index.md`, `docs/l2-runbooks/00-index.md`, `docs/common-issues.md`, `docs/quick-ref-l2.md`, `docs/admin-setup-macos/00-overview.md` extensions",
    "",
    "**Defer (out of v1.10 scope):**",
    "- Multi-tenant PSSO (PSSO-FUT-03) -- deferred to its own architectural milestone; not touched here",
    "- Azure Files / Cloud Kerberos TGT -- currently in limited preview (as of 2026-06-15); document with prominent preview callout only, not as a GA feature",
    "- Standalone Kerberos extension deployment without PSSO -- out of v1.10 scope; guide 10 covers PSSO-combined deployment only",
    "- Standalone NUAL deployment guide -- PSSO-FUT-01 scope is a surgical table update only; a full NUAL guide is post-v1.10 if demand surfaces",
    "- `Temporary` value deep-dive for `NewUserAuthorizationMode` -- note existence only (Apple schema defines it; Intune Settings Catalog does not surface it); defer coverage",
    "",
    "### Architecture Approach",
    "",
    "v1.10 extends the existing layered hub-and-spoke documentation architecture without introducing new structural patterns. Two new admin-setup guides (10 and optionally 11) continue the zero-padded numeric sequence. Two new L2 runbooks (28 and 29) continue the globally sequential runbook numbering. All new files follow the existing naming conventions verified by direct directory inspection. Surgical edits to four existing files (guides 08, 09, `00-overview.md`, capability matrix) are tightly scoped. Navigation hubs are updated last in a dedicated integration phase per the navigation-last invariant.",
    "",
    "**Major components and v1.10 actions:**",
    "1. `docs/admin-setup-macos/` -- ADD `10-kerberos-sso-extension.md`; ADD `11-graph-api-platform-credential.md` (if Option A); SURGICAL EDIT guides 08, 09, and `00-overview.md`",
    "2. `docs/l2-runbooks/` -- ADD `28-macos-kerberos-sso-investigation.md`; ADD `29-macos-graph-credential-investigation.md`; EXTEND `00-index.md` (navigation-last)",
    "3. `docs/reference/macos-capability-matrix.md` -- ADD Kerberos SSO Extension row; ATOMIC UPDATE `check-phase-63.mjs` V-63-08 blob hash in the same commit",
    "4. `docs/_glossary-macos.md` -- ADD Kerberos SSO Extension entry; ADD or EXTEND Platform Credential entry",
    "5. `docs/index.md` + nav hubs -- EXTEND macOS sections (navigation-last, dedicated integration phase)",
    "6. `scripts/validation/` -- ADD `v1.10-milestone-audit.mjs` + sidecar + `check-phase-83..NN.mjs` + CI workflow + `_lib/frozen-at-close.mjs` V19 SHA entry (two-atom harness-lineage-bump pattern)",
    "",
    "**Gray area -- Graph API doc placement (Option A vs B):**",
    "Option A (`docs/admin-setup-macos/11-graph-api-platform-credential.md`) is recommended: keeps the complete macOS Platform SSO documentation surface in one numbered sequence (07-11), consistent with the PSSO-FUT-02 deferred-cleanup framing. Option B (`docs/operations/platform-credential/00-graph-api.md`) is architecturally defensible if the intended audience is primarily automation engineers and if future milestones expect additional Graph-side management guides. The roadmap author should confirm this placement at requirements time.",
    "",
    "### Critical Pitfalls",
    "",
    "The following pitfalls are load-bearing for execution. Phase plans that do not explicitly address them have a documented failure mode.",
    "",
    "1. **Wrong Kerberos extension identifier (K-1)** -- Using `com.microsoft.CompanyPortalMac.ssoextension` (the PSSO identifier) in the Kerberos profile breaks both extensions on device. Prevention: every Kerberos profile example must source `com.apple.AppSSOKerberos.KerberosExtension` directly from Apple developer documentation, not from guide 09 prose. Include a side-by-side identifier comparison table.",
    "",
    "2. **Wrong Kerberos payload type (K-5)** -- Using `Type: Redirect` (the PSSO value) instead of `Type: Credential` in the Kerberos profile causes silent TGT acquisition failure. Prevention: every Kerberos plist example uses `Type = Credential`; include a callout: \"The most common configuration copy-error from PSSO guides.\"",
    "",
    "3. **Graph API DELETE without safety callout (G-2)** -- Documenting the DELETE endpoint without a `> [!WARNING]` blockquote risks accidental fleet-wide PSSO re-registration via bulk-delete scripts. Prevention: the `[!WARNING]` callout is a hard requirement in the phase plan; follow the `03-esp-policy.md` pattern; automation examples include a `-WhatIf` or dry-run step.",
    "",
    "4. **Capability matrix edit without atomic harness validator update (DI-2)** -- Any change to `macos-capability-matrix.md` breaks V-63-08 (blob hash `e91d7f9e001bb7ff4dc56a4ca98c84868fbf0716`) in `check-phase-63.mjs` unless the validator is updated in the same commit. Prevention: run `git hash-object` pre- and post-edit; update V-63-08 atomically; never split into separate commits.",
    "",
    "5. **Pre-existing chain-red masked via CHAIN_SKIP (DI-3)** -- Adding phases 58-66 and 73 to `CHAIN_SKIP` in the v1.10 apex to make it appear green violates the \"do NOT mask\" doctrine from `v1.9-DEFERRED-CLEANUP.md`. Prevention: schedule a chain-health decision at roadmap time (Option A: dedicated chain-health phase before harness-lineage bump; Option B: route forward with documented rationale and honest FAIL-count reporting). Option C (CHAIN_SKIP expansion) is prohibited.",
    "",
    "6. **Navigation-last invariant broken (DI-1)** -- Any content-authoring phase that also edits `docs/index.md`, `common-issues.md`, or runbook index files creates forward-links to files that may not yet exist, causing C13 broken-link failures. Prevention: every content-authoring phase plan must contain an explicit prohibition clause for nav-hub files; a dedicated integration phase owns all nav-hub edits.",
    "",
    "---",
    "",
    "## Implications for Roadmap",
    "",
    "Based on combined research, the recommended phase structure is 4-5 content phases (83-86 or 83-87 depending on chain-health bundling decision) plus a harness close phase. The suggested build order is grounded in the dependency topology from ARCHITECTURE.md and the pitfall-prevention requirements from PITFALLS.md.",
    "",
    "### Phase 83 -- Kerberos SSO Extension Guide + Guide 09 Surgical Edit",
    "",
    "**Rationale:** The Kerberos guide is the largest new content deliverable and has the most cross-link dependencies. Guide 09's deferred-item note creates a dangling forward-reference that must be replaced with a live link as soon as guide 10 exists. The glossary entry must be committed before any downstream cross-link to it is asserted by a validator. The `00-overview.md` Mermaid extension ensures discoverability from the admin setup entry point.",
    "",
    "**Delivers:**",
    "- `docs/admin-setup-macos/10-kerberos-sso-extension.md` (new)",
    "- Guide 09 `## Kerberos SSO Extension (Coexistence)` surgical edit (one sentence replaced with forward link)",
    "- `docs/admin-setup-macos/00-overview.md` Mermaid + bullet list extension (node 10)",
    "- `docs/_glossary-macos.md` Kerberos SSO Extension entry",
    "",
    "**Addresses features:** PSSO-FUT-04 (Kerberos guide); Surface 1 table-stakes + differentiators from FEATURES.md",
    "",
    "**Must avoid:** K-1 (wrong identifier), K-2 (extension conflation), K-3 (stale CLI syntax -- use `app-sso platform -s` and `klist`; no `app-sso diagnose`), K-4 (out-of-scope AD content), K-5 (wrong payload type Redirect vs Credential), DI-1 (no nav-hub edits in this phase)",
    "",
    "**Research flag:** SKIP -- all technical facts are HIGH confidence and verified. Phase plan should cite Apple developer docs directly for `com.apple.AppSSOKerberos.KerberosExtension`.",
    "",
    "---",
    "",
    "### Phase 84 -- Graph API Platform Credential Doc + NUAL Key Table Update",
    "",
    "**Rationale:** The Graph API doc and NUAL table update are independent of the Kerberos guide and of each other. Both surfaces have fully resolved research questions -- no execution-time research is needed. The Graph API doc placement (Option A vs B) must be decided before this phase begins.",
    "",
    "**Delivers:**",
    "- Graph API doc at confirmed location (Option A: `docs/admin-setup-macos/11-graph-api-platform-credential.md`, recommended)",
    "- Guide 08 `## New User At Login Window` surgical edit: add `NewUserAuthorizationMode` and `UserAuthorizationMode` plist key literals to existing Settings Catalog table; remove deferred-item callout blockquote",
    "- `docs/admin-setup-macos/00-overview.md` extension for guide 11 (if Option A)",
    "- Glossary extension for Platform Credential Graph API term (if warranted)",
    "",
    "**Addresses features:** PSSO-FUT-02 (Graph API doc); PSSO-FUT-01 (NUAL key literal closure); Surfaces 2 and 3 features from FEATURES.md",
    "",
    "**Must avoid:** G-1 (verify `v1.0` endpoint namespace before drafting -- confirmed GA, but cite source in phase plan), G-2 (`[!WARNING]` callout on DELETE is mandatory), G-3 (include explicit permission table distinguishing read vs delete scopes), N-1 (plist key literals must cite Apple `device-management` schema -- already verified, include citation), N-2 (surgical edit only -- do not rewrite the NUAL section), DI-1 (navigation-last)",
    "",
    "**Research flag:** SKIP -- Graph API GA status confirmed HIGH; NUAL key literals confirmed HIGH. Two execution-time verification checks are lookups, not research phases.",
    "",
    "---",
    "",
    "### Phase 85 -- Capability Matrix + L2 Runbooks",
    "",
    "**Rationale:** L2 runbooks reference the admin guides from Phases 83 and 84; they must not be authored before those guides exist. The capability matrix edit requires the Kerberos guide to exist before adding cross-link rows. The pre-edit anchor inventory must be performed as the first task of this phase, and the harness validator update for V-63-08 must be in the same atomic commit as the matrix file change.",
    "",
    "**Delivers:**",
    "- Pre-edit anchor inventory artifact for `docs/reference/macos-capability-matrix.md` (committed as a phase plan artifact, e.g., `85-ANCHOR-INVENTORY.md`)",
    "- Kerberos SSO Extension row added to `docs/reference/macos-capability-matrix.md`",
    "- `check-phase-63.mjs` V-63-08 blob hash updated atomically with the matrix file change",
    "- `docs/l2-runbooks/28-macos-kerberos-sso-investigation.md` (new)",
    "- `docs/l2-runbooks/29-macos-graph-credential-investigation.md` (new)",
    "- `docs/l2-runbooks/00-index.md` extended with rows 28 and 29 + escalation mapping (runbook-internal hub updated before the top-level `docs/index.md`)",
    "",
    "**Must avoid:** DI-2 (atomic matrix + validator update -- never split into separate commits), DI-1 (top-level `docs/index.md` is NOT touched here)",
    "",
    "**Research flag:** SKIP -- L2 runbook structure and capability matrix row format are established in v1.9.",
    "",
    "---",
    "",
    "### Phase 86 -- Nav Hub Integration (+ Optional Chain-Health Pass)",
    "",
    "**Rationale:** Navigation-last convention requires all content files to exist before any nav-hub links to them. The optional chain-health sub-deliverable (frozen-aware conversion of check-phase-{58-66, 73}.mjs) is placed here rather than in the harness-lineage-bump phase to preserve the atomic indivisibility of harness Atom 2.",
    "",
    "**Delivers:**",
    "- `docs/index.md` macOS Admin Setup table extended (guide 10 and guide 11 rows); Desktop Engineering L2 table extended (L2 #28 and #29 rows)",
    "- `docs/common-issues.md` macOS section extended (Kerberos escalation entry)",
    "- `docs/quick-ref-l2.md` macOS section extended (`app-sso platform -s` and `klist` commands)",
    "- `docs/decision-trees/06-macos-triage.md` Kerberos SSO extension leaf node added (routes to L2 #28)",
    "- OPTIONAL: chain-health sub-deliverable -- frozen-aware conversion of 10 legacy validators; `73-RETRO-INVENTORY.md` restoration",
    "",
    "**Must avoid:** DI-1 (this is the designated nav-hub phase -- all nav-hub edits happen here and only here), DI-3 (if chain-health is included, it must be a distinct sub-phase scope and must not be folded into harness Atom 2)",
    "",
    "**Harness decision note for roadmap author:** If the chain-health pass is included in Phase 86, check-phase-86.mjs should assert chain-apex exits 0 with 0 FAIL. If chain-health is deferred, the harness-lineage-bump phase must document the exact pre-existing FAIL count (10 FAILs: phases 58-66 and 73) in the audit summary, and the v1.10 apex must not include those phases in `CHAIN_SKIP`.",
    "",
    "**Research flag:** SKIP -- nav-hub integration follows established patterns from v1.9 Phases 80-81.",
    "",
    "---",
    "",
    "### Phase 87 -- Harness Lineage Bump + Terminal Re-Audit + Milestone Close",
    "",
    "**Rationale:** The harness-lineage bump is always the final phase in the Path-A lineage. It follows the two-atomic-commit pattern from v1.7 Phase 70 through v1.9 Phase 82. V19 (v1.9 close-gate SHA) must be pinned in `_lib/frozen-at-close.mjs` BEFORE any `check-phase-83.mjs` is authored -- this is a hard ordering constraint that the roadmap must encode.",
    "",
    "**Delivers (Atom 1):** `scripts/validation/v1.10-milestone-audit.mjs` + `v1.10-audit-allowlist.json` + BASELINE_14 in `regenerate-supervision-pins.mjs` -- 3 files indivisible",
    "",
    "**Delivers (Atom 2):** `check-phase-83..86.mjs` (or 87) + `audit-harness-v1.10-integrity.yml` + `_lib/frozen-at-close.mjs` V19 SHA entry -- indivisible set",
    "",
    "**Terminal re-audit:** 3-axis stacking (Axis 1 fresh-clone local, Axis 2 Linux GHA, Axis 3 fresh sub-agent) per v1.9 Phase 82 precedent",
    "",
    "**Close-gate:** two-commit chicken-and-egg pattern (Commit A SHA placeholder fill + Commit B `v1.10-MILESTONE-AUDIT.md` NEW + `v1.10-DEFERRED-CLEANUP.md` + 4-doc traceability closure)",
    "",
    "**Must avoid:** DI-3 (no `CHAIN_SKIP` expansion for legacy FAILs 58-66/73 unless resolved by chain-health pass in Phase 86; if not resolved, audit summary must report exact count as pre-existing legacy FAILs)",
    "",
    "**Research flag:** SKIP -- Path-A harness-lineage-bump pattern is fully documented and has been executed successfully in v1.7, v1.8, and v1.9.",
    "",
    "---",
    "",
    "### Phase Ordering Rationale",
    "",
    "- **Kerberos guide first (Phase 83):** Largest new file, most downstream cross-links, and the guide 09 forward-reference must be satisfied before the guide 09 surgical edit is committed. Authoring the large content deliverable first reduces pipeline risk.",
    "- **Graph API + NUAL second (Phase 84):** Independent of Phase 83; sequential execution per the worktree-unreliable constraint documented in MEMORY.md. Bundling two smaller surfaces in one phase is efficient given their shared independence from Kerberos.",
    "- **Capability matrix + L2 runbooks third (Phase 85):** These reference content from Phases 83 and 84 and must come after. The V-63-08 atomic update requirement means the matrix phase must be scheduled as a distinct phase rather than rolled into Phase 83/84.",
    "- **Navigation-last fourth (Phase 86):** Mandatory per the navigation-last invariant established across all prior milestones.",
    "- **Harness close last (Phase 87):** Mandatory per the Path-A pattern; the two-atom commit pattern requires all content phases to be complete before Atom 1 is authored.",
    "",
    "### Research Flags",
    "",
    "Phases with well-documented patterns (skip `--research-phase`):",
    "- **Phase 83 (Kerberos guide):** All technical facts verified HIGH confidence. No further research needed. Phase plan must cite Apple developer docs as source for extension identifier and payload type.",
    "- **Phase 84 (Graph API + NUAL):** All technical facts verified HIGH confidence. Two execution-time verification checks are lookups, not research phases.",
    "- **Phase 85 (Matrix + L2 runbooks):** Established patterns; no research needed.",
    "- **Phase 86 (Nav hub):** Established patterns; no research needed.",
    "- **Phase 87 (Harness):** Path-A pattern fully documented; no research needed.",
    "",
    "Execution-time checks (not blockers, must be completed before specific phase tasks):",
    "- **Phase 84 pre-task:** Verify Intune Settings Catalog shows `NewUserAuthorizationMode` and `UserAuthorizationMode` under `Authentication > Extensible Single Sign On (SSO) > Platform SSO`. Cross-reference Microsoft Learn PSSO scenarios page (last updated 2026-05-11). If display names have drifted from Apple schema key names, document divergence explicitly in the guide 08 table rather than silently reconciling.",
    "- **Phase 84 pre-task:** Confirm exact minimum Graph API delete permission scope (`UserAuthMethod-PlatformCred.ReadWrite` vs `UserAuthenticationMethod.ReadWrite`) against live permissions reference at `https://learn.microsoft.com/en-us/graph/permissions-reference`.",
    "- **Phase 83 pre-task:** Verify `app-sso` subcommand surface against the macOS man page before incorporating any `app-sso` command other than `platform -s` in guide 10. Default diagnostic pair: `app-sso platform -s` + `klist`. Include `app-sso kerberos` subcommands only if verified against a live macOS 14.6+ binary during Phase 83 execution.",
    "",
    "---",
    "",
    "## Confidence Assessment",
    "",
    "| Area | Confidence | Notes |",
    "|------|------------|-------|",
    "| Stack | HIGH | Extension identifier, Graph API GA status, NUAL key literals, macOS version floors all verified from authoritative primary sources. No inference used. |",
    "| Features | HIGH | Deliverable scope derived directly from v1.9 deferred-cleanup backlog (PSSO-FUT-01/02/04). Scope boundaries locked by adversarial-review decision. |",
    "| Architecture | HIGH | All integration points verified by direct file inspection. Runbook numbering (28/29), guide numbering (10/11), and harness lineage structure (Path-A 8th milestone) confirmed from directory listings and PROJECT.md. |",
    "| Pitfalls | HIGH | All pitfalls verified from authoritative documentation (K-1, K-5, G-1, N-1) or are documented pre-existing risks from v1.9 lineage (DI-2 V-63-08, DI-3 chain-red, DI-1 navigation-last). No speculative pitfalls. |",
    "",
    "**Overall confidence:** HIGH",
    "",
    "### Gaps to Address",
    "",
    "Execution-time checks -- not research blockers. Do not delay roadmap creation. Must be addressed within the specified phases.",
    "",
    "- **NUAL Settings Catalog display-name second-pass (Phase 84):** Intune's live Settings Catalog may expose NUAL keys under slightly different display names than the Microsoft Learn PSSO scenarios page (last updated 2026-05-11). Apple schema key names (`NewUserAuthorizationMode`, `UserAuthorizationMode`) are confirmed correct. If Intune display names diverge, document both the Apple key literal and the Intune display name explicitly in the guide 08 table.",
    "",
    "- **Graph API delete permission least-privilege second-pass (Phase 84):** Two permission names appear for the minimum delete scope: `UserAuthenticationMethod.ReadWrite` (delegated) and the narrower `UserAuthMethod-PlatformCred.ReadWrite`. The permission table must resolve this to a single least-privilege recommendation, verified against the live permissions reference page.",
    "",
    "- **`app-sso` Kerberos-specific subcommand surface (Phase 83):** `app-sso platform -s` is HIGH confidence for verifying PSSO + Kerberos TGT state. The standalone `app-sso kerberos` subcommand is MEDIUM confidence (man page reference, no Microsoft Learn endorsement). Default to `app-sso platform -s` + `klist`; include `app-sso kerberos` only if verified against a live macOS 14.6+ binary during Phase 83 execution.",
    "",
    "- **Graph API doc placement decision (roadmap decision):** Option A (`docs/admin-setup-macos/11-graph-api-platform-credential.md`) is recommended. Confirm as a named decision in the roadmap (e.g., `GRAPH-API-PLACEMENT: Option A`) to prevent execution-time drift. Key factors if `/adversarial-review` is invoked: primary audience (Intune admin vs automation engineer); whether v1.11+ is expected to produce additional Graph-side management guides.",
    "",
    "- **Azure Files Cloud Kerberos preview callout (Phase 83):** Verify at guide 10 execution time whether the Azure Files + PSSO Kerberos TGT feature has graduated from limited preview (status per Microsoft Entra tutorial as of 2026-06-15). If still preview, document with a `> [!IMPORTANT]` callout and `azurefiles@microsoft.com` contact. If GA, remove the preview callout.",
    "",
    "- **V19 close-gate SHA for `frozen-at-close.mjs` (Phase 87 pre-condition):** Identify via `git log --all --grep=\"close-gate\" --grep=\"v1.9\" --all-match -1`. Must be pinned in `_lib/frozen-at-close.mjs` before any `check-phase-83.mjs` is authored. This is a hard ordering constraint for Phase 87 pre-work.",
    "",
    "---",
    "",
    "## Sources",
    "",
    "### Primary (HIGH confidence -- all verified 2026-06-22)",
    "",
    "- Apple device-management GitHub -- `com.apple.extensiblesso.yaml` (release branch): authoritative MDM plist key names for all three NUAL keys, Kerberos extension identifier confirmation -- https://github.com/apple/device-management/blob/release/mdm/profiles/com.apple.extensiblesso.yaml",
    "- Apple Device Policy Explorer -- `com.apple.extensiblesso` (release branch): cross-verification of Apple schema key names -- https://appledevicepolicy.tools/policy-explorer/detail?type=com.apple.extensiblesso&branch=release",
    "- Microsoft Learn -- Enable Kerberos SSO in Platform SSO (updated 2026-06-15): extension identifier, mobileconfig examples, macOS 14.6 version floor, Company Portal version requirements, `app-sso platform -s` diagnostic output -- https://learn.microsoft.com/en-us/entra/identity/devices/device-join-macos-platform-single-sign-on-kerberos-configuration",
    "- Microsoft Learn -- Platform SSO scenarios for macOS (updated 2026-05-13): NUAL Settings Catalog display names, `custom_tgt_setting` TGT mapping key -- https://learn.microsoft.com/en-us/intune/device-configuration/settings-catalog/configure-platform-sso-scenarios-macos",
    "- Microsoft Learn -- `platformCredentialAuthenticationMethod` resource (v1.0, updated 2026-01-28): resource properties, relationship, GA status confirmation -- https://learn.microsoft.com/en-us/graph/api/resources/platformcredentialauthenticationmethod?view=graph-rest-1.0",
    "- Microsoft Learn -- List operation (v1.0, updated 2025-11-13): permissions matrix for read operations -- https://learn.microsoft.com/en-us/graph/api/platformcredentialauthenticationmethod-list?view=graph-rest-1.0",
    "- Microsoft Learn -- Delete operation (v1.0, updated 2025-11-08): permissions matrix for delete operations, MFA re-prompt behavior -- https://learn.microsoft.com/en-us/graph/api/platformcredentialauthenticationmethod-delete?view=graph-rest-1.0",
    "- Microsoft Graph docs-contrib repository (Context7, /microsoftgraph/microsoft-graph-docs-contrib): confirmed `api-reference/v1.0/` path prefix for all three operations; permissions reference confirmation",
    "- Apple Support -- Kerberos SSO extension deployment guide: https://support.apple.com/guide/deployment/kerberos-sso-extension-depe6a1cda64/web",
    "- Apple Platform Deployment -- Extensible Single Sign-on Kerberos payload settings: https://support.apple.com/guide/deployment/dep13c5cfdf9/web",
    "",
    "### Secondary (HIGH confidence -- internal v1.9 lineage, verified by direct file inspection)",
    "",
    "- `.planning/milestones/v1.9-DEFERRED-CLEANUP.md` -- PSSO-FUT-01/02/04 backlog items; PRE-EXISTING-CHAIN-RED-AT-HEAD-01 (10 FAILs in check-phase-{58-66, 73})",
    "- `docs/admin-setup-macos/09-enterprise-sso-plugin-migration.md` line ~148 -- exact deferred-item sentence to be replaced in Phase 83",
    "- `docs/admin-setup-macos/08-auth-methods-deep-dive.md` lines 270-287 -- existing NUAL Settings Catalog table with deferred-item callout",
    "- `scripts/validation/check-phase-63.mjs` lines 202-220 -- V-63-08 byte-unchanged baseline blob hash `e91d7f9e001bb7ff4dc56a4ca98c84868fbf0716`",
    "- `docs/l2-runbooks/` directory listing -- highest file confirmed `27-macos-sso-investigation.md`; next free slots 28 and 29",
    "- `docs/admin-setup-macos/00-overview.md` -- existing Mermaid sequence structure; highest node confirmed as 09",
    "- `docs/reference/macos-capability-matrix.md` -- `## Authentication` section confirmed (8 rows, Platform SSO auth methods); Kerberos SSO Extension row absent",
    "- `docs/operations/00-index.md` -- 5 existing H2 subtrees; structure confirmed for Option B analysis",
    "- `docs/admin-setup-apv1/03-esp-policy.md` lines 101-105 -- `> [!WARNING]` blockquote pattern for destructive operations",
    "",
    "---",
    "*Research completed: 2026-06-22*",
    "*Ready for roadmap: yes*",
]

with open(out, "w", encoding="utf-8") as f:
    f.write("\n".join(lines))

size = len(open(out, encoding="utf-8").read())
print(f"Written {size} chars to {out}")
